// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-HDElzCnaTn3WaYO1wqnDYCaF9XBCWbQ',
    appId: '1:830168816747:web:58623383e2f6321426652e',
    messagingSenderId: '830168816747',
    projectId: 'shopping-app-cb4cf',
    authDomain: 'shopping-app-cb4cf.firebaseapp.com',
    databaseURL: 'https://shopping-app-cb4cf-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-app-cb4cf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChF6AzUomFCY0U4I-zgu7uWYHTeDDENYk',
    appId: '1:830168816747:android:024fb65cccf39d5326652e',
    messagingSenderId: '830168816747',
    projectId: 'shopping-app-cb4cf',
    databaseURL: 'https://shopping-app-cb4cf-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-app-cb4cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqjVlL9uI-7xbDx2h7bTpypAogwCqSKjA',
    appId: '1:830168816747:ios:eac884ec0b32b24326652e',
    messagingSenderId: '830168816747',
    projectId: 'shopping-app-cb4cf',
    databaseURL: 'https://shopping-app-cb4cf-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-app-cb4cf.firebasestorage.app',
    iosBundleId: 'com.example.shoppingMax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqjVlL9uI-7xbDx2h7bTpypAogwCqSKjA',
    appId: '1:830168816747:ios:eac884ec0b32b24326652e',
    messagingSenderId: '830168816747',
    projectId: 'shopping-app-cb4cf',
    databaseURL: 'https://shopping-app-cb4cf-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-app-cb4cf.firebasestorage.app',
    iosBundleId: 'com.example.shoppingMax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXhF1d_RdaASso9pgPr3jW5UVnKwwTKJc',
    appId: '1:830168816747:web:3f2435b5adc5924526652e',
    messagingSenderId: '830168816747',
    projectId: 'shopping-app-cb4cf',
    authDomain: 'shopping-app-cb4cf.firebaseapp.com',
    databaseURL: 'https://shopping-app-cb4cf-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-app-cb4cf.firebasestorage.app',
  );

}